import = ["~/dots/alacritty/tokyonight.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[font]
size = 7.0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[window]
dynamic_title = false
opacity = 1
dynamic_padding = false
#decorations = "None"
decorations = "Buttonless"

[window.padding]
x = 12
y = 12

[selection]
save_to_clipboard = true

