import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
  TERM = "xterm-256color"

[font]
  size = 11.5
  normal = { family = "Blex Nerd Font", style = "Regular" }

[window]
  padding = { y = 27 }
  decorations = "transparent"
  dynamic_title = true

[cursor]
  style= "Block"

[selection]
  save_to_clipboard = true
