require 'plugins.blink'
require 'plugins.cloak'
require 'plugins.conform'
require 'plugins.gitsigns'
require 'plugins.mini'
require 'plugins.oil'
require 'plugins.snacks'
require 'plugins.treesitter'
